---
- hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  roles:
    - fresco_module
    echo "Run the playbook using terminal"
    service ssh status
    systemctl stop ssh
    sudo bash .install.sh
